### ISSUE TITLE
Could not find 'node'. Node.js is required to be installed to link Truffle projects. 

### ISSUE THREAD

**Issue by Thakshinss** [bayesianinstitute/EHR-Using-Blockchain#1]
file:///home/thadkshin/Pictures/Screenshots/Screenshot%20from%202023-04-10%2022-17-25.png

**Comment by Thakshinss** [comment]
can you help me to solve this problem,it is showing in truffle contract section
![Screenshot from 2023-04-10 22-17-25](https://user-images.githubusercontent.com/101057362/230952041-775ccc1f-47b9-4e34-8009-71f4276bca1d.png)

**Comment by faizack** [comment]
> Refere

Please Install Node JS from https://nodejs.org/en/download
